using System.Collections;
using System.Collections.Generic;
using UnityEngine;

#region EnumCollection
public enum GENDER{MALE, FEMALE}
public enum CONTEXT_RELATION{LOVE, FAMILY, FRIEND, COWORKER, STRANGER}
public enum CONTEXT_MOMENT{APART, REUNION, FIRST_CONTACT, FORGIVE, LIFE_DEATH, EMOTIONAL}
public enum CONTEXT_ENVIRONMENT{WORKING_PLACE, TRANSPORT_STATION, HOUSE, STREET, SCHOOL, FIELD, RELAX}
public enum PIECE_TYPE {KING, QUEEN, BISHOP, KNIGHT, ROOK, PAWN, NEUTRAL};
public enum PLAYER_SIDE{WHITE, BLACK};
public enum CONTROL_TYPE{AI, PLAYER};
public enum MOVE_TYPE{MOVE, CAPTURE}
#endregion
