using System.Collections;
using System.Collections.Generic;
using UnityEngine;

#region EnumCollection
public enum GENDER{MALE, FEMALE}
public enum GENERATION{BABY, YOUTH, TEEN, GROWN, MIDDLE, OLD, DEAD}
public enum CONTEXT_RELATION{LIKE=0, FAMILY=1, FRIEND=2, COWORKER=3, STRANGER=4}
public enum CONTEXT_MOMENT{APART=0, REUNION=1, FIRST_CONTACT=2, FORGIVE=3}
public enum CONTEXT_ENVIRONMENT{TRANSPORT=0, HOME=1, STREET=2, SCHOOL=3}
public enum PIECE_TYPE {KING, QUEEN, BISHOP, KNIGHT, ROOK, PAWN, NEUTRAL, TOMB};
public enum PLAYER_SIDE{WHITE, BLACK};
public enum CONTROL_TYPE{AI, PLAYER};
public enum MOVE_TYPE{MOVE, CAPTURE}
public enum END_CONDITON{ALL_HUG, NO_PIECE}
#endregion
